//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HM_Sushhnost
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// НС.
    /// </summary>
    // *** Start programmer edit section *** (НС CustomAttributes)

    // *** End programmer edit section *** (НС CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НСE", new string[] {
            "id as \'Id\'",
            "DateTime as \'Date time\'",
            "name as \'Name\'",
            "ПриборыЗд as \'Приборы зд\'",
            "ПриборыЗд.id as \'Id\'"}, Hidden=new string[] {
            "ПриборыЗд.id"})]
    [MasterViewDefineAttribute("НСE", "ПриборыЗд", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "id")]
    [View("НСL", new string[] {
            "id as \'Id\'",
            "DateTime as \'Date time\'",
            "name as \'Name\'",
            "ПриборыЗд.id as \'Id\'"})]
    public class НС : ICSSoft.STORMNET.DataObject
    {
        
        private int fid;
        
        private System.DateTime fDateTime;
        
        private IIS.HM_Sushhnost.ТипыНС fname;
        
        private IIS.HM_Sushhnost.ПриборыЗд fПриборыЗд;
        
        // *** Start programmer edit section *** (НС CustomMembers)

        // *** End programmer edit section *** (НС CustomMembers)

        
        /// <summary>
        /// DateTime.
        /// </summary>
        // *** Start programmer edit section *** (НС.DateTime CustomAttributes)

        // *** End programmer edit section *** (НС.DateTime CustomAttributes)
        public virtual System.DateTime DateTime
        {
            get
            {
                // *** Start programmer edit section *** (НС.DateTime Get start)

                // *** End programmer edit section *** (НС.DateTime Get start)
                System.DateTime result = this.fDateTime;
                // *** Start programmer edit section *** (НС.DateTime Get end)

                // *** End programmer edit section *** (НС.DateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НС.DateTime Set start)

                // *** End programmer edit section *** (НС.DateTime Set start)
                this.fDateTime = value;
                // *** Start programmer edit section *** (НС.DateTime Set end)

                // *** End programmer edit section *** (НС.DateTime Set end)
            }
        }
        
        /// <summary>
        /// id.
        /// </summary>
        // *** Start programmer edit section *** (НС.id CustomAttributes)

        // *** End programmer edit section *** (НС.id CustomAttributes)
        public virtual int id
        {
            get
            {
                // *** Start programmer edit section *** (НС.id Get start)

                // *** End programmer edit section *** (НС.id Get start)
                int result = this.fid;
                // *** Start programmer edit section *** (НС.id Get end)

                // *** End programmer edit section *** (НС.id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НС.id Set start)

                // *** End programmer edit section *** (НС.id Set start)
                this.fid = value;
                // *** Start programmer edit section *** (НС.id Set end)

                // *** End programmer edit section *** (НС.id Set end)
            }
        }
        
        /// <summary>
        /// name.
        /// </summary>
        // *** Start programmer edit section *** (НС.name CustomAttributes)

        // *** End programmer edit section *** (НС.name CustomAttributes)
        public virtual IIS.HM_Sushhnost.ТипыНС name
        {
            get
            {
                // *** Start programmer edit section *** (НС.name Get start)

                // *** End programmer edit section *** (НС.name Get start)
                IIS.HM_Sushhnost.ТипыНС result = this.fname;
                // *** Start programmer edit section *** (НС.name Get end)

                // *** End programmer edit section *** (НС.name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НС.name Set start)

                // *** End programmer edit section *** (НС.name Set start)
                this.fname = value;
                // *** Start programmer edit section *** (НС.name Set end)

                // *** End programmer edit section *** (НС.name Set end)
            }
        }
        
        /// <summary>
        /// НС.
        /// </summary>
        // *** Start programmer edit section *** (НС.ПриборыЗд CustomAttributes)

        // *** End programmer edit section *** (НС.ПриборыЗд CustomAttributes)
        [PropertyStorage(new string[] {
                "ПриборыЗд"})]
        [NotNull()]
        public virtual IIS.HM_Sushhnost.ПриборыЗд ПриборыЗд
        {
            get
            {
                // *** Start programmer edit section *** (НС.ПриборыЗд Get start)

                // *** End programmer edit section *** (НС.ПриборыЗд Get start)
                IIS.HM_Sushhnost.ПриборыЗд result = this.fПриборыЗд;
                // *** Start programmer edit section *** (НС.ПриборыЗд Get end)

                // *** End programmer edit section *** (НС.ПриборыЗд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НС.ПриборыЗд Set start)

                // *** End programmer edit section *** (НС.ПриборыЗд Set start)
                this.fПриборыЗд = value;
                // *** Start programmer edit section *** (НС.ПриборыЗд Set end)

                // *** End programmer edit section *** (НС.ПриборыЗд Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НСE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НСE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НСE", typeof(IIS.HM_Sushhnost.НС));
                }
            }
            
            /// <summary>
            /// "НСL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НСL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НСL", typeof(IIS.HM_Sushhnost.НС));
                }
            }
        }
    }
}
