//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HM_Sushhnost
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Показания пр.
    /// </summary>
    // *** Start programmer edit section *** (ПоказанияПр CustomAttributes)

    // *** End programmer edit section *** (ПоказанияПр CustomAttributes)
    [AutoAltered()]
    [Caption("Показания пр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПоказанияПрE", new string[] {
            "id as \'Id\'",
            "DateTime as \'Date time\'",
            "T as \'T\'",
            "P as \'P\'",
            "M as \'M\'",
            "Q as \'Q\'",
            "ПриборыЗд as \'Приборы зд\'",
            "ПриборыЗд.id as \'Id\'"}, Hidden=new string[] {
            "ПриборыЗд.id"})]
    [MasterViewDefineAttribute("ПоказанияПрE", "ПриборыЗд", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "id")]
    [View("ПоказанияПрL", new string[] {
            "id as \'Id\'",
            "DateTime as \'Date time\'",
            "T as \'T\'",
            "P as \'P\'",
            "M as \'M\'",
            "Q as \'Q\'",
            "ПриборыЗд.id as \'Id\'"})]
    public class ПоказанияПр : ICSSoft.STORMNET.DataObject
    {
        
        private int fid;
        
        private System.DateTime fDateTime;
        
        private double fT;
        
        private double fP;
        
        private double fM;
        
        private bool fQ;
        
        private IIS.HM_Sushhnost.ПриборыЗд fПриборыЗд;
        
        // *** Start programmer edit section *** (ПоказанияПр CustomMembers)

        // *** End programmer edit section *** (ПоказанияПр CustomMembers)

        
        /// <summary>
        /// DateTime.
        /// </summary>
        // *** Start programmer edit section *** (ПоказанияПр.DateTime CustomAttributes)

        // *** End programmer edit section *** (ПоказанияПр.DateTime CustomAttributes)
        public virtual System.DateTime DateTime
        {
            get
            {
                // *** Start programmer edit section *** (ПоказанияПр.DateTime Get start)

                // *** End programmer edit section *** (ПоказанияПр.DateTime Get start)
                System.DateTime result = this.fDateTime;
                // *** Start programmer edit section *** (ПоказанияПр.DateTime Get end)

                // *** End programmer edit section *** (ПоказанияПр.DateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПоказанияПр.DateTime Set start)

                // *** End programmer edit section *** (ПоказанияПр.DateTime Set start)
                this.fDateTime = value;
                // *** Start programmer edit section *** (ПоказанияПр.DateTime Set end)

                // *** End programmer edit section *** (ПоказанияПр.DateTime Set end)
            }
        }
        
        /// <summary>
        /// id.
        /// </summary>
        // *** Start programmer edit section *** (ПоказанияПр.id CustomAttributes)

        // *** End programmer edit section *** (ПоказанияПр.id CustomAttributes)
        public virtual int id
        {
            get
            {
                // *** Start programmer edit section *** (ПоказанияПр.id Get start)

                // *** End programmer edit section *** (ПоказанияПр.id Get start)
                int result = this.fid;
                // *** Start programmer edit section *** (ПоказанияПр.id Get end)

                // *** End programmer edit section *** (ПоказанияПр.id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПоказанияПр.id Set start)

                // *** End programmer edit section *** (ПоказанияПр.id Set start)
                this.fid = value;
                // *** Start programmer edit section *** (ПоказанияПр.id Set end)

                // *** End programmer edit section *** (ПоказанияПр.id Set end)
            }
        }
        
        /// <summary>
        /// M.
        /// </summary>
        // *** Start programmer edit section *** (ПоказанияПр.M CustomAttributes)

        // *** End programmer edit section *** (ПоказанияПр.M CustomAttributes)
        public virtual double M
        {
            get
            {
                // *** Start programmer edit section *** (ПоказанияПр.M Get start)

                // *** End programmer edit section *** (ПоказанияПр.M Get start)
                double result = this.fM;
                // *** Start programmer edit section *** (ПоказанияПр.M Get end)

                // *** End programmer edit section *** (ПоказанияПр.M Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПоказанияПр.M Set start)

                // *** End programmer edit section *** (ПоказанияПр.M Set start)
                this.fM = value;
                // *** Start programmer edit section *** (ПоказанияПр.M Set end)

                // *** End programmer edit section *** (ПоказанияПр.M Set end)
            }
        }
        
        /// <summary>
        /// P.
        /// </summary>
        // *** Start programmer edit section *** (ПоказанияПр.P CustomAttributes)

        // *** End programmer edit section *** (ПоказанияПр.P CustomAttributes)
        public virtual double P
        {
            get
            {
                // *** Start programmer edit section *** (ПоказанияПр.P Get start)

                // *** End programmer edit section *** (ПоказанияПр.P Get start)
                double result = this.fP;
                // *** Start programmer edit section *** (ПоказанияПр.P Get end)

                // *** End programmer edit section *** (ПоказанияПр.P Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПоказанияПр.P Set start)

                // *** End programmer edit section *** (ПоказанияПр.P Set start)
                this.fP = value;
                // *** Start programmer edit section *** (ПоказанияПр.P Set end)

                // *** End programmer edit section *** (ПоказанияПр.P Set end)
            }
        }
        
        /// <summary>
        /// Q.
        /// </summary>
        // *** Start programmer edit section *** (ПоказанияПр.Q CustomAttributes)

        // *** End programmer edit section *** (ПоказанияПр.Q CustomAttributes)
        public virtual bool Q
        {
            get
            {
                // *** Start programmer edit section *** (ПоказанияПр.Q Get start)

                // *** End programmer edit section *** (ПоказанияПр.Q Get start)
                bool result = this.fQ;
                // *** Start programmer edit section *** (ПоказанияПр.Q Get end)

                // *** End programmer edit section *** (ПоказанияПр.Q Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПоказанияПр.Q Set start)

                // *** End programmer edit section *** (ПоказанияПр.Q Set start)
                this.fQ = value;
                // *** Start programmer edit section *** (ПоказанияПр.Q Set end)

                // *** End programmer edit section *** (ПоказанияПр.Q Set end)
            }
        }
        
        /// <summary>
        /// T.
        /// </summary>
        // *** Start programmer edit section *** (ПоказанияПр.T CustomAttributes)

        // *** End programmer edit section *** (ПоказанияПр.T CustomAttributes)
        public virtual double T
        {
            get
            {
                // *** Start programmer edit section *** (ПоказанияПр.T Get start)

                // *** End programmer edit section *** (ПоказанияПр.T Get start)
                double result = this.fT;
                // *** Start programmer edit section *** (ПоказанияПр.T Get end)

                // *** End programmer edit section *** (ПоказанияПр.T Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПоказанияПр.T Set start)

                // *** End programmer edit section *** (ПоказанияПр.T Set start)
                this.fT = value;
                // *** Start programmer edit section *** (ПоказанияПр.T Set end)

                // *** End programmer edit section *** (ПоказанияПр.T Set end)
            }
        }
        
        /// <summary>
        /// Показания пр.
        /// </summary>
        // *** Start programmer edit section *** (ПоказанияПр.ПриборыЗд CustomAttributes)

        // *** End programmer edit section *** (ПоказанияПр.ПриборыЗд CustomAttributes)
        [PropertyStorage(new string[] {
                "ПриборыЗд"})]
        [NotNull()]
        public virtual IIS.HM_Sushhnost.ПриборыЗд ПриборыЗд
        {
            get
            {
                // *** Start programmer edit section *** (ПоказанияПр.ПриборыЗд Get start)

                // *** End programmer edit section *** (ПоказанияПр.ПриборыЗд Get start)
                IIS.HM_Sushhnost.ПриборыЗд result = this.fПриборыЗд;
                // *** Start programmer edit section *** (ПоказанияПр.ПриборыЗд Get end)

                // *** End programmer edit section *** (ПоказанияПр.ПриборыЗд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПоказанияПр.ПриборыЗд Set start)

                // *** End programmer edit section *** (ПоказанияПр.ПриборыЗд Set start)
                this.fПриборыЗд = value;
                // *** Start programmer edit section *** (ПоказанияПр.ПриборыЗд Set end)

                // *** End programmer edit section *** (ПоказанияПр.ПриборыЗд Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПоказанияПрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоказанияПрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоказанияПрE", typeof(IIS.HM_Sushhnost.ПоказанияПр));
                }
            }
            
            /// <summary>
            /// "ПоказанияПрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоказанияПрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоказанияПрL", typeof(IIS.HM_Sushhnost.ПоказанияПр));
                }
            }
        }
    }
}
