//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HM_Sushhnost
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Прибор учёта.
    /// </summary>
    // *** Start programmer edit section *** (ПриборУчёта CustomAttributes)

    // *** End programmer edit section *** (ПриборУчёта CustomAttributes)
    [AutoAltered()]
    [Caption("Прибор учёта")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПриборУчётаE", new string[] {
            "id as \'Id\'",
            "name as \'Name\'",
            "ПриборыЗд as \'Приборы зд\'",
            "ПриборыЗд.id as \'Id\'"}, Hidden=new string[] {
            "ПриборыЗд.id"})]
    [MasterViewDefineAttribute("ПриборУчётаE", "ПриборыЗд", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "id")]
    [View("ПриборУчётаL", new string[] {
            "id as \'Id\'",
            "name as \'Name\'",
            "ПриборыЗд.id as \'Id\'"})]
    public class ПриборУчёта : ICSSoft.STORMNET.DataObject
    {
        
        private int fid;
        
        private string fname;
        
        private IIS.HM_Sushhnost.ПриборыЗд fПриборыЗд;
        
        // *** Start programmer edit section *** (ПриборУчёта CustomMembers)

        // *** End programmer edit section *** (ПриборУчёта CustomMembers)

        
        /// <summary>
        /// id.
        /// </summary>
        // *** Start programmer edit section *** (ПриборУчёта.id CustomAttributes)

        // *** End programmer edit section *** (ПриборУчёта.id CustomAttributes)
        public virtual int id
        {
            get
            {
                // *** Start programmer edit section *** (ПриборУчёта.id Get start)

                // *** End programmer edit section *** (ПриборУчёта.id Get start)
                int result = this.fid;
                // *** Start programmer edit section *** (ПриборУчёта.id Get end)

                // *** End programmer edit section *** (ПриборУчёта.id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборУчёта.id Set start)

                // *** End programmer edit section *** (ПриборУчёта.id Set start)
                this.fid = value;
                // *** Start programmer edit section *** (ПриборУчёта.id Set end)

                // *** End programmer edit section *** (ПриборУчёта.id Set end)
            }
        }
        
        /// <summary>
        /// name.
        /// </summary>
        // *** Start programmer edit section *** (ПриборУчёта.name CustomAttributes)

        // *** End programmer edit section *** (ПриборУчёта.name CustomAttributes)
        [StrLen(255)]
        public virtual string name
        {
            get
            {
                // *** Start programmer edit section *** (ПриборУчёта.name Get start)

                // *** End programmer edit section *** (ПриборУчёта.name Get start)
                string result = this.fname;
                // *** Start programmer edit section *** (ПриборУчёта.name Get end)

                // *** End programmer edit section *** (ПриборУчёта.name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборУчёта.name Set start)

                // *** End programmer edit section *** (ПриборУчёта.name Set start)
                this.fname = value;
                // *** Start programmer edit section *** (ПриборУчёта.name Set end)

                // *** End programmer edit section *** (ПриборУчёта.name Set end)
            }
        }
        
        /// <summary>
        /// Прибор учёта.
        /// </summary>
        // *** Start programmer edit section *** (ПриборУчёта.ПриборыЗд CustomAttributes)

        // *** End programmer edit section *** (ПриборУчёта.ПриборыЗд CustomAttributes)
        [PropertyStorage(new string[] {
                "ПриборыЗд"})]
        [NotNull()]
        public virtual IIS.HM_Sushhnost.ПриборыЗд ПриборыЗд
        {
            get
            {
                // *** Start programmer edit section *** (ПриборУчёта.ПриборыЗд Get start)

                // *** End programmer edit section *** (ПриборУчёта.ПриборыЗд Get start)
                IIS.HM_Sushhnost.ПриборыЗд result = this.fПриборыЗд;
                // *** Start programmer edit section *** (ПриборУчёта.ПриборыЗд Get end)

                // *** End programmer edit section *** (ПриборУчёта.ПриборыЗд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборУчёта.ПриборыЗд Set start)

                // *** End programmer edit section *** (ПриборУчёта.ПриборыЗд Set start)
                this.fПриборыЗд = value;
                // *** Start programmer edit section *** (ПриборУчёта.ПриборыЗд Set end)

                // *** End programmer edit section *** (ПриборУчёта.ПриборыЗд Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПриборУчётаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриборУчётаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриборУчётаE", typeof(IIS.HM_Sushhnost.ПриборУчёта));
                }
            }
            
            /// <summary>
            /// "ПриборУчётаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриборУчётаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриборУчётаL", typeof(IIS.HM_Sushhnost.ПриборУчёта));
                }
            }
        }
    }
}
