//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HM_Sushhnost
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Приборы зд.
    /// </summary>
    // *** Start programmer edit section *** (ПриборыЗд CustomAttributes)

    // *** End programmer edit section *** (ПриборыЗд CustomAttributes)
    [AutoAltered()]
    [Caption("Приборы зд")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПриборыЗдE", new string[] {
            "id as \'Id\'",
            "Mmax as \'Mmax\'",
            "Mmin as \'Mmin\'",
            "Tmax as \'Tmax\'",
            "Tmin as \'Tmin\'",
            "Pmax as \'Pmax\'",
            "UrovZar as \'Urov zar\'",
            "PrivT as \'Priv T\'",
            "PrivP as \'Priv P\'",
            "PrivM as \'Priv M\'",
            "Здание as \'Здание\'",
            "Здание.name as \'Name\'"}, Hidden=new string[] {
            "Здание.name"})]
    [MasterViewDefineAttribute("ПриборыЗдE", "Здание", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "name")]
    [View("ПриборыЗдL", new string[] {
            "id as \'Id\'",
            "Mmax as \'Mmax\'",
            "Mmin as \'Mmin\'",
            "Tmax as \'Tmax\'",
            "Tmin as \'Tmin\'",
            "Pmax as \'Pmax\'",
            "UrovZar as \'Urov zar\'",
            "PrivT as \'Priv T\'",
            "PrivP as \'Priv P\'",
            "PrivM as \'Priv M\'",
            "Здание.name as \'Name\'"})]
    public class ПриборыЗд : ICSSoft.STORMNET.DataObject
    {
        
        private int fid;
        
        private double fMmax;
        
        private double fMmin;
        
        private double fTmax;
        
        private double fTmin;
        
        private double fPmax;
        
        private double fUrovZar;
        
        private bool fPrivT;
        
        private bool fPrivP;
        
        private bool fPrivM;
        
        private IIS.HM_Sushhnost.Здание fЗдание;
        
        // *** Start programmer edit section *** (ПриборыЗд CustomMembers)

        // *** End programmer edit section *** (ПриборыЗд CustomMembers)

        
        /// <summary>
        /// id.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.id CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.id CustomAttributes)
        public virtual int id
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.id Get start)

                // *** End programmer edit section *** (ПриборыЗд.id Get start)
                int result = this.fid;
                // *** Start programmer edit section *** (ПриборыЗд.id Get end)

                // *** End programmer edit section *** (ПриборыЗд.id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.id Set start)

                // *** End programmer edit section *** (ПриборыЗд.id Set start)
                this.fid = value;
                // *** Start programmer edit section *** (ПриборыЗд.id Set end)

                // *** End programmer edit section *** (ПриборыЗд.id Set end)
            }
        }
        
        /// <summary>
        /// Mmax.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.Mmax CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.Mmax CustomAttributes)
        public virtual double Mmax
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.Mmax Get start)

                // *** End programmer edit section *** (ПриборыЗд.Mmax Get start)
                double result = this.fMmax;
                // *** Start programmer edit section *** (ПриборыЗд.Mmax Get end)

                // *** End programmer edit section *** (ПриборыЗд.Mmax Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.Mmax Set start)

                // *** End programmer edit section *** (ПриборыЗд.Mmax Set start)
                this.fMmax = value;
                // *** Start programmer edit section *** (ПриборыЗд.Mmax Set end)

                // *** End programmer edit section *** (ПриборыЗд.Mmax Set end)
            }
        }
        
        /// <summary>
        /// Mmin.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.Mmin CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.Mmin CustomAttributes)
        public virtual double Mmin
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.Mmin Get start)

                // *** End programmer edit section *** (ПриборыЗд.Mmin Get start)
                double result = this.fMmin;
                // *** Start programmer edit section *** (ПриборыЗд.Mmin Get end)

                // *** End programmer edit section *** (ПриборыЗд.Mmin Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.Mmin Set start)

                // *** End programmer edit section *** (ПриборыЗд.Mmin Set start)
                this.fMmin = value;
                // *** Start programmer edit section *** (ПриборыЗд.Mmin Set end)

                // *** End programmer edit section *** (ПриборыЗд.Mmin Set end)
            }
        }
        
        /// <summary>
        /// Pmax.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.Pmax CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.Pmax CustomAttributes)
        public virtual double Pmax
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.Pmax Get start)

                // *** End programmer edit section *** (ПриборыЗд.Pmax Get start)
                double result = this.fPmax;
                // *** Start programmer edit section *** (ПриборыЗд.Pmax Get end)

                // *** End programmer edit section *** (ПриборыЗд.Pmax Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.Pmax Set start)

                // *** End programmer edit section *** (ПриборыЗд.Pmax Set start)
                this.fPmax = value;
                // *** Start programmer edit section *** (ПриборыЗд.Pmax Set end)

                // *** End programmer edit section *** (ПриборыЗд.Pmax Set end)
            }
        }
        
        /// <summary>
        /// PrivM.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.PrivM CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.PrivM CustomAttributes)
        public virtual bool PrivM
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.PrivM Get start)

                // *** End programmer edit section *** (ПриборыЗд.PrivM Get start)
                bool result = this.fPrivM;
                // *** Start programmer edit section *** (ПриборыЗд.PrivM Get end)

                // *** End programmer edit section *** (ПриборыЗд.PrivM Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.PrivM Set start)

                // *** End programmer edit section *** (ПриборыЗд.PrivM Set start)
                this.fPrivM = value;
                // *** Start programmer edit section *** (ПриборыЗд.PrivM Set end)

                // *** End programmer edit section *** (ПриборыЗд.PrivM Set end)
            }
        }
        
        /// <summary>
        /// PrivP.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.PrivP CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.PrivP CustomAttributes)
        public virtual bool PrivP
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.PrivP Get start)

                // *** End programmer edit section *** (ПриборыЗд.PrivP Get start)
                bool result = this.fPrivP;
                // *** Start programmer edit section *** (ПриборыЗд.PrivP Get end)

                // *** End programmer edit section *** (ПриборыЗд.PrivP Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.PrivP Set start)

                // *** End programmer edit section *** (ПриборыЗд.PrivP Set start)
                this.fPrivP = value;
                // *** Start programmer edit section *** (ПриборыЗд.PrivP Set end)

                // *** End programmer edit section *** (ПриборыЗд.PrivP Set end)
            }
        }
        
        /// <summary>
        /// PrivT.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.PrivT CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.PrivT CustomAttributes)
        public virtual bool PrivT
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.PrivT Get start)

                // *** End programmer edit section *** (ПриборыЗд.PrivT Get start)
                bool result = this.fPrivT;
                // *** Start programmer edit section *** (ПриборыЗд.PrivT Get end)

                // *** End programmer edit section *** (ПриборыЗд.PrivT Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.PrivT Set start)

                // *** End programmer edit section *** (ПриборыЗд.PrivT Set start)
                this.fPrivT = value;
                // *** Start programmer edit section *** (ПриборыЗд.PrivT Set end)

                // *** End programmer edit section *** (ПриборыЗд.PrivT Set end)
            }
        }
        
        /// <summary>
        /// Tmax.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.Tmax CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.Tmax CustomAttributes)
        public virtual double Tmax
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.Tmax Get start)

                // *** End programmer edit section *** (ПриборыЗд.Tmax Get start)
                double result = this.fTmax;
                // *** Start programmer edit section *** (ПриборыЗд.Tmax Get end)

                // *** End programmer edit section *** (ПриборыЗд.Tmax Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.Tmax Set start)

                // *** End programmer edit section *** (ПриборыЗд.Tmax Set start)
                this.fTmax = value;
                // *** Start programmer edit section *** (ПриборыЗд.Tmax Set end)

                // *** End programmer edit section *** (ПриборыЗд.Tmax Set end)
            }
        }
        
        /// <summary>
        /// Tmin.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.Tmin CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.Tmin CustomAttributes)
        public virtual double Tmin
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.Tmin Get start)

                // *** End programmer edit section *** (ПриборыЗд.Tmin Get start)
                double result = this.fTmin;
                // *** Start programmer edit section *** (ПриборыЗд.Tmin Get end)

                // *** End programmer edit section *** (ПриборыЗд.Tmin Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.Tmin Set start)

                // *** End programmer edit section *** (ПриборыЗд.Tmin Set start)
                this.fTmin = value;
                // *** Start programmer edit section *** (ПриборыЗд.Tmin Set end)

                // *** End programmer edit section *** (ПриборыЗд.Tmin Set end)
            }
        }
        
        /// <summary>
        /// UrovZar.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.UrovZar CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.UrovZar CustomAttributes)
        public virtual double UrovZar
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.UrovZar Get start)

                // *** End programmer edit section *** (ПриборыЗд.UrovZar Get start)
                double result = this.fUrovZar;
                // *** Start programmer edit section *** (ПриборыЗд.UrovZar Get end)

                // *** End programmer edit section *** (ПриборыЗд.UrovZar Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.UrovZar Set start)

                // *** End programmer edit section *** (ПриборыЗд.UrovZar Set start)
                this.fUrovZar = value;
                // *** Start programmer edit section *** (ПриборыЗд.UrovZar Set end)

                // *** End programmer edit section *** (ПриборыЗд.UrovZar Set end)
            }
        }
        
        /// <summary>
        /// Приборы зд.
        /// </summary>
        // *** Start programmer edit section *** (ПриборыЗд.Здание CustomAttributes)

        // *** End programmer edit section *** (ПриборыЗд.Здание CustomAttributes)
        [PropertyStorage(new string[] {
                "Здание"})]
        [NotNull()]
        public virtual IIS.HM_Sushhnost.Здание Здание
        {
            get
            {
                // *** Start programmer edit section *** (ПриборыЗд.Здание Get start)

                // *** End programmer edit section *** (ПриборыЗд.Здание Get start)
                IIS.HM_Sushhnost.Здание result = this.fЗдание;
                // *** Start programmer edit section *** (ПриборыЗд.Здание Get end)

                // *** End programmer edit section *** (ПриборыЗд.Здание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриборыЗд.Здание Set start)

                // *** End programmer edit section *** (ПриборыЗд.Здание Set start)
                this.fЗдание = value;
                // *** Start programmer edit section *** (ПриборыЗд.Здание Set end)

                // *** End programmer edit section *** (ПриборыЗд.Здание Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПриборыЗдE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриборыЗдE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриборыЗдE", typeof(IIS.HM_Sushhnost.ПриборыЗд));
                }
            }
            
            /// <summary>
            /// "ПриборыЗдL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриборыЗдL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриборыЗдL", typeof(IIS.HM_Sushhnost.ПриборыЗд));
                }
            }
        }
    }
}
