//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HM_Sushhnost
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Типы НС.
    /// </summary>
    // *** Start programmer edit section *** (ТипыНС CustomAttributes)

    // *** End programmer edit section *** (ТипыНС CustomAttributes)
    public enum ТипыНС
    {
        
        // *** Start programmer edit section *** (ТипыНС.UrovZaryda CustomAttributes)

        // *** End programmer edit section *** (ТипыНС.UrovZaryda CustomAttributes)
        UrovZaryda,
        
        // *** Start programmer edit section *** (ТипыНС.PrivT CustomAttributes)

        // *** End programmer edit section *** (ТипыНС.PrivT CustomAttributes)
        PrivT,
        
        // *** Start programmer edit section *** (ТипыНС.PrivP CustomAttributes)

        // *** End programmer edit section *** (ТипыНС.PrivP CustomAttributes)
        PrivP,
        
        // *** Start programmer edit section *** (ТипыНС.PrivM CustomAttributes)

        // *** End programmer edit section *** (ТипыНС.PrivM CustomAttributes)
        PrivM,
    }
}
