//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HM_Sushhnost
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Человек.
    /// </summary>
    // *** Start programmer edit section *** (Человек CustomAttributes)

    // *** End programmer edit section *** (Человек CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЧеловекE", new string[] {
            "id as \'Id\'"})]
    [View("ЧеловекL", new string[] {
            "id as \'Id\'"})]
    public class Человек : ICSSoft.STORMNET.DataObject
    {
        
        private int fid;
        
        // *** Start programmer edit section *** (Человек CustomMembers)

        // *** End programmer edit section *** (Человек CustomMembers)

        
        /// <summary>
        /// id.
        /// </summary>
        // *** Start programmer edit section *** (Человек.id CustomAttributes)

        // *** End programmer edit section *** (Человек.id CustomAttributes)
        public virtual int id
        {
            get
            {
                // *** Start programmer edit section *** (Человек.id Get start)

                // *** End programmer edit section *** (Человек.id Get start)
                int result = this.fid;
                // *** Start programmer edit section *** (Человек.id Get end)

                // *** End programmer edit section *** (Человек.id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Человек.id Set start)

                // *** End programmer edit section *** (Человек.id Set start)
                this.fid = value;
                // *** Start programmer edit section *** (Человек.id Set end)

                // *** End programmer edit section *** (Человек.id Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЧеловекE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧеловекE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧеловекE", typeof(IIS.HM_Sushhnost.Человек));
                }
            }
            
            /// <summary>
            /// "ЧеловекL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧеловекL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧеловекL", typeof(IIS.HM_Sushhnost.Человек));
                }
            }
        }
    }
}
