




CREATE TABLE ПриборУчёта (
 primaryKey UUID NOT NULL,
 id INT NULL,
 name VARCHAR(255) NULL,
 ПриборыЗд UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Человек (
 primaryKey UUID NOT NULL,
 id INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Здание (
 primaryKey UUID NOT NULL,
 id INT NULL,
 name VARCHAR(255) NULL,
 Человек UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE НС (
 primaryKey UUID NOT NULL,
 DateTime TIMESTAMP(3) NULL,
 id INT NULL,
 name VARCHAR(10) NULL,
 ПриборыЗд UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ПоказанияПр (
 primaryKey UUID NOT NULL,
 DateTime TIMESTAMP(3) NULL,
 id INT NULL,
 M DOUBLE PRECISION NULL,
 P DOUBLE PRECISION NULL,
 Q BOOLEAN NULL,
 T DOUBLE PRECISION NULL,
 ПриборыЗд UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ПриборыЗд (
 primaryKey UUID NOT NULL,
 id INT NULL,
 Mmax DOUBLE PRECISION NULL,
 Mmin DOUBLE PRECISION NULL,
 Pmax DOUBLE PRECISION NULL,
 PrivM BOOLEAN NULL,
 PrivP BOOLEAN NULL,
 PrivT BOOLEAN NULL,
 Tmax DOUBLE PRECISION NULL,
 Tmin DOUBLE PRECISION NULL,
 UrovZar DOUBLE PRECISION NULL,
 Здание UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE ПриборУчёта ADD CONSTRAINT FKb46991a316badd7a302a7307fe6a694986d9b3fa FOREIGN KEY (ПриборыЗд) REFERENCES ПриборыЗд; 
CREATE INDEX Indexb46991a316badd7a302a7307fe6a694986d9b3fa on ПриборУчёта (ПриборыЗд); 

 ALTER TABLE Здание ADD CONSTRAINT FK8d93049bf69bb9e63badad9b6b169564c53b999b FOREIGN KEY (Человек) REFERENCES Человек; 
CREATE INDEX Index8d93049bf69bb9e63badad9b6b169564c53b999b on Здание (Человек); 

 ALTER TABLE НС ADD CONSTRAINT FKd0469ad8feb6f7c6d96c2dc92323442c2b2e912d FOREIGN KEY (ПриборыЗд) REFERENCES ПриборыЗд; 
CREATE INDEX Indexd0469ad8feb6f7c6d96c2dc92323442c2b2e912d on НС (ПриборыЗд); 

 ALTER TABLE ПоказанияПр ADD CONSTRAINT FK912ffc6766cae51515813f2971b3929fe0592a13 FOREIGN KEY (ПриборыЗд) REFERENCES ПриборыЗд; 
CREATE INDEX Index912ffc6766cae51515813f2971b3929fe0592a13 on ПоказанияПр (ПриборыЗд); 

 ALTER TABLE ПриборыЗд ADD CONSTRAINT FKb07eec06bdf88cd04e95f37760e34fc91270327b FOREIGN KEY (Здание) REFERENCES Здание; 
CREATE INDEX Indexb07eec06bdf88cd04e95f37760e34fc91270327b on ПриборыЗд (Здание); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

